# Generated by Django 6.0.1 on 2026-01-17 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactInfo",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255, verbose_name="Название")),
                ("email", models.EmailField(max_length=254, unique=True, verbose_name="Email")),
                ("phone", models.CharField(blank=True, max_length=20, null=True, verbose_name="Телефон")),
                ("address", models.TextField(blank=True, verbose_name="Адрес")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "контакт",
                "verbose_name_plural": "контакты",
            },
        ),
    ]
