# Generated by Django 6.0.1 on 2026-01-17 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_contactinfo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactinfo",
            name="email",
            field=models.EmailField(max_length=254, verbose_name="Email"),
        ),
    ]
